
USE master;
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'VETERINARIA')
BEGIN
    ALTER DATABASE VETERINARIA SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE VETERINARIA;
END
CREATE DATABASE VETERINARIA;
GO

USE VETERINARIA;
GO

-- DDL: CREACION DE TABLAS PREVIAS
CREATE TABLE CLIENTE(
    id_cliente INT IDENTITY (1,1) PRIMARY KEY,
    apellido VARCHAR(50) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    direccion VARCHAR(50) NOT NULL,
    telefono VARCHAR(20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    CONSTRAINT uq_cliente_email UNIQUE(email)
);

CREATE TABLE VETERINARIO(
    id_veterinario INT IDENTITY (1,1) PRIMARY KEY,
    apellido VARCHAR(50) NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    direccion VARCHAR(50) NOT NULL,
    telefono VARCHAR (20) NOT NULL,
    email VARCHAR(50) NOT NULL,
    CONSTRAINT uq_veterinario_telefono UNIQUE(telefono),
    CONSTRAINT uq_veterinario_email UNIQUE(email)
);
